format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/vk83/prerelease/apps/spack/1.1/release/linux-x86_64_v4/access3-2026.03.001-cd45w7dm4eqz6pkatowevzx7p5gukarz/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: 88c8c223ac9c4f7150f3530394dfc3a0
    md5: 48e2c3dc39ce69e64012d3805e1022db
